[package]
name = "ln"
version = "0.0.1"
authors = []
license = "MIT"
build = "../../common/mkmain.rs"

[lib]
name = "uu_ln"
path = "src/ln.rs"

[dependencies]
clap = "2.32.0"
libc = "0.2.42"
uucore = "0.0.2"

[[bin]]
name = "ln"
path = "../../common/uumain.rs"
